import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar  from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'${inter.className} flex h-screen items-start justify-between'}>
        <Sidebar></Sidebar>

        <div className="flex flex-col items-start flex-1">
            <Navbar></Navbar>
            
            <main className="">
              {children}
            </main>
          </div>
          </body>
        
        
    </html>
  );
}
