import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Senusa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          "${inter.className} flex h-screen items-start justify-between"
        }
      >
        <div className="flex flex-col items-start flex-1">
          <main className="flex-column justify-content items-center w-full ">
            {children}
          </main>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
